/**
 * Renders a generated brief.
 *
 * Three things this deliberately does, all of them about not letting a
 * machine-written paragraph pass for knowledge:
 *
 *   - It is labelled as generated, every time, not once in a footnote.
 *   - Every bullet shows what it came from. "Says who?" is one glance away,
 *     and the citation is a link when the source has a URL.
 *   - It says how old the underlying conversations are, not how recently the
 *     summary ran. A brief regenerated this morning from material last touched
 *     in July is stale, and the date that matters is July.
 */
import { formatDistanceToNowStrict } from 'date-fns'
import { Chip, GapFlag, Muted, type Tone } from '@/components/ui'
import { label, type BriefItem, type BriefItemKind } from '@/lib/domain'
import type { BriefRow, TranscriptRow } from '@/lib/briefs'

const KIND_TONE: Record<BriefItemKind, Tone> = {
  decision: 'green',
  open_issue: 'amber',
  risk: 'red',
  change: 'blue',
}

/** Consequence order, not alphabetical: what is broken reads before what was settled. */
const KIND_ORDER: BriefItemKind[] = ['risk', 'open_issue', 'change', 'decision']

function Citations({
  ids,
  transcripts,
}: {
  ids: string[]
  transcripts: Map<string, TranscriptRow>
}) {
  const found = ids.map((id) => transcripts.get(id)).filter((t): t is TranscriptRow => Boolean(t))
  if (found.length === 0) return null

  return (
    <div className="mt-1 flex flex-wrap items-center gap-1.5">
      <Muted>from</Muted>
      {found.map((t) => {
        const when = t.occurredAt ? t.occurredAt.toISOString().slice(0, 10) : 'undated'
        const text = `${t.title} · ${when}`
        return t.url ? (
          <a
            key={t.id}
            href={t.url}
            target="_blank"
            rel="noreferrer"
            className="text-[11px] underline decoration-dotted underline-offset-2"
            style={{ color: 'var(--brand-2)' }}
          >
            {text}
          </a>
        ) : (
          <span key={t.id} className="text-[11px]" style={{ color: 'var(--muted)' }}>
            {text}
          </span>
        )
      })}
    </div>
  )
}

export function Brief({
  brief,
  transcripts,
  transcriptCount,
}: {
  brief: BriefRow | null
  /** Every transcript for this entity, for resolving citations. */
  transcripts: TranscriptRow[]
  transcriptCount: number
}) {
  const byId = new Map(transcripts.map((t) => [t.id, t]))

  if (!brief) {
    return (
      <div className="mt-2 text-[12px]">
        {transcriptCount > 0 ? (
          <GapFlag title="Conversations are attached but nothing has been summarised from them yet.">
            {transcriptCount} conversation{transcriptCount === 1 ? '' : 's'} attached, no brief yet
          </GapFlag>
        ) : (
          <Muted>No conversations attached.</Muted>
        )}
      </div>
    )
  }

  const grouped = KIND_ORDER.map((kind) => ({
    kind,
    items: brief.items.filter((i: BriefItem) => i.kind === kind),
  })).filter((g) => g.items.length > 0)

  const covers = brief.coversThrough
  const age = covers ? formatDistanceToNowStrict(covers, { addSuffix: true }) : null
  // Staleness is decided in the read model, against the same three-week
  // threshold the assessments use.
  const stale = brief.stale

  return (
    <div
      className="mt-2 rounded-lg border p-3"
      style={{ background: 'var(--raised)', borderColor: 'var(--line)' }}
    >
      <div className="mb-2 flex flex-wrap items-center gap-2">
        <span
          className="text-[10px] font-bold uppercase tracking-[0.06em]"
          style={{ color: 'var(--brand-2)' }}
        >
          From conversations
        </span>
        <Chip tone="slate" title={`Generated by ${brief.model}`}>
          generated summary
        </Chip>
        {age ? (
          stale ? (
            <GapFlag title="The newest conversation behind this brief is over three weeks old.">
              newest source {age}
            </GapFlag>
          ) : (
            <Muted>newest source {age}</Muted>
          )
        ) : null}
      </div>

      {grouped.length === 0 ? (
        <p className="m-0 text-[12.5px]" style={{ color: 'var(--muted)' }}>
          Nothing worth reporting was found in {brief.transcriptCount} conversation
          {brief.transcriptCount === 1 ? '' : 's'}. That is an answer, not a failure.
        </p>
      ) : (
        <div className="flex flex-col gap-2.5">
          {grouped.map((g) => (
            <div key={g.kind}>
              <Chip tone={KIND_TONE[g.kind]}>{label('briefItemKind', g.kind)}</Chip>
              <ul className="mt-1 mb-0 list-disc pl-5">
                {g.items.map((item, ix) => (
                  <li key={`${g.kind}-${ix}`} className="mt-1 text-[12.5px] leading-relaxed">
                    {item.text}
                    <Citations ids={item.sourceTranscriptIds} transcripts={byId} />
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      )}

      <div className="mt-2.5 border-t pt-2" style={{ borderColor: 'var(--line)' }}>
        <Muted>
          Written by a model from {brief.transcriptCount} conversation
          {brief.transcriptCount === 1 ? '' : 's'}. It is not an assessment, and nobody has
          signed off on it — read the sources before repeating any of it.
        </Muted>
      </div>
    </div>
  )
}
